/*
   -- New project --
   
   To compile this code using RemoteXY library 4.1.8 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.18.03 or later version;
     - for iOS 1.14.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/

//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////

// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    

// RemoteXY select connection mode and include library 
#define REMOTEXY_MODE__ESP32CORE_BLE

#include <BLEDevice.h>

// RemoteXY connection settings 
#define REMOTEXY_BLUETOOTH_NAME "RemoteXY"


#include <RemoteXY.h>

// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t const PROGMEM RemoteXY_CONF_PROGMEM[] =   // 304 bytes V19 
  { 255,0,0,12,0,41,1,19,0,0,0,0,31,1,106,200,3,1,0,0,
  7,0,70,12,33,18,18,16,26,37,0,70,70,33,18,18,16,26,37,0,
  129,5,13,40,12,64,17,66,108,105,110,107,101,114,0,129,53,13,51,12,
  64,17,70,101,114,110,108,105,99,104,116,0,129,25,85,51,12,64,17,68,
  114,101,104,122,97,104,108,0,131,32,179,40,14,2,17,2,31,80,97,103,
  101,32,49,0,38,71,19,105,62,62,56,16,2,24,135,0,0,0,0,0,
  0,122,67,0,0,112,66,0,0,240,65,0,0,112,65,24,114,112,109,0,
  7,0,68,17,30,76,74,1,8,36,70,16,143,18,18,16,26,37,0,131,
  34,182,40,14,2,17,2,31,80,97,103,101,32,50,0,26,70,72,144,18,
  18,16,26,37,0,129,9,125,37,12,64,17,195,150,76,32,48,46,51,0,
  129,62,125,37,12,64,17,195,150,76,32,49,46,56,0,129,33,10,46,12,
  64,17,66,97,116,116,101,114,105,101,0,5,0,129,11,5,88,12,64,17,
  75,195,188,104,108,109,105,116,116,101,108,116,101,109,112,0,131,31,182,40,
  14,2,17,2,31,77,97,105,110,32,112,97,103,101,0,41,129,39,92,28,
  12,64,17,84,97,110,107,0,66,17,28,70,40,131,2,24,66,16,114,70,
  40,131,2,24 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // output variables
  uint8_t turn_signal_w; // from 0 to 1
  uint8_t high_beam_w; // from 0 to 1
  int16_t rpm_w; // from 0 to 250
  float batt_volt_w;
  uint8_t oil_03_w; // from 0 to 1
  uint8_t oil_18_w; // from 0 to 1
  int8_t water_temp_w; // from 0 to 100
  int8_t tank_level_w; // from 0 to 100

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////




void setup() 
{
  RemoteXY_Init ();  // initialization by macros 
  
  
  // TODO you setup code
  
}

void loop() 
{ 
  RemoteXYEngine.handler ();   
   
  
  // TODO you loop code
  // use the RemoteXY structure for data transfer
  // do not call delay(), use instead RemoteXYEngine.delay() 

}

