//     * **************************************************************** *
//   *                                                                      *
// *          (C) Copyright Matthias Schär, all rights reserved               *
//   *                                                                      *
//     * **************************************************************** *
/// @file Backlight.c

/// @brief Software-PWM backlight driver for the TPS61169 (PJ12 / BL_CTRL).
///
/// TIM17 update interrupt fires 100 000 times/s.
/// Each call increments an internal counter (0..99).
/// The GPIO is set HIGH on counter == 0 and LOW when the counter reaches
/// the programmed duty value, giving a clean 1 kHz PWM signal.
#include "Backlight.h"
#include "main.h"

#include "stm32h7xx_hal.h"

// * ************************************************************************ *
// *                                DEFINES                                   *
// * ************************************************************************ *

#define BL_PWM_RESOLUTION  100U   /* ticks per PWM period (= % granularity) */

// * ************************************************************************ *
// *                             STATIC VARIABLES                             *
// * ************************************************************************ *

extern TIM_HandleTypeDef htim17;  /* generated by CubeMX in main.c */

/// Current duty cycle (0..BL_PWM_RESOLUTION).  Written from main context,
/// read from ISR -- uint8_t writes are atomic on CM7, no critical section needed.
static volatile uint8_t s_duty   = 0U;
static volatile uint8_t s_ticks  = 0U;

// * ************************************************************************ *
// *                             GLOBAL FUNCTIONS                             *
// * ************************************************************************ *

void BacklightInit(void)
{
  s_duty  = 0U;
  s_ticks = 0U;
  /* Pin starts LOW (off).  The ISR will drive it from here on. */
  HAL_GPIO_WritePin(BL_CTRL_GPIO_Port, BL_CTRL_Pin, GPIO_PIN_RESET);
  HAL_TIM_Base_Start_IT(&htim17);
}

void BacklightSetDuty(uint8_t duty)
{
  if (duty > BACKLIGHT_DUTY_MAX) {
    duty = BACKLIGHT_DUTY_MAX;
  }
  s_duty = duty;
}

// * ************************************************************************ *
// *                              LOCAL FUNCTIONS                             *
// * ************************************************************************ *

/// @brief TIM17 period-elapsed callback -- 100 kHz software PWM tick.
///        Overrides the weak HAL default.
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  if (htim->Instance != TIM17) {
    return;
  }

  uint8_t ticks = s_ticks;
  uint8_t duty  = s_duty;

  if (ticks == 0U) {
    /* Start of a new PWM period: drive HIGH if duty > 0 */
    if (duty > 0U) {
      HAL_GPIO_WritePin(BL_CTRL_GPIO_Port, BL_CTRL_Pin, GPIO_PIN_SET);
    }
  }

  if (ticks >= duty) {
    /* Duty threshold passed: drive LOW */
    HAL_GPIO_WritePin(BL_CTRL_GPIO_Port, BL_CTRL_Pin, GPIO_PIN_RESET);
  }

  if (++ticks >= BL_PWM_RESOLUTION) {
    ticks = 0U;
  }
  s_ticks = ticks;
}
