/**
  ******************************************************************************
  * @file    FreeRTOSConfig.h
  * @brief   FreeRTOS configuration for STM32H747I-DISCO CM7 + TouchGFX.
  *
  * Manually maintained (not generated by STM32CubeMX).
  ******************************************************************************
  */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

/* -------------------------------------------------------------------------- */
/* Hardware / clocks                                                          */
/* -------------------------------------------------------------------------- */

/* CM7 core clock as configured by SystemClock_Config() (400 MHz). */
#define configCPU_CLOCK_HZ                       ( ( unsigned long ) 400000000 )

/* 1 kHz tick keeps parity with HAL_GetTick() so HAL_Delay()-style code keeps
 * working when scheduler is running. */
#define configTICK_RATE_HZ                       ( ( TickType_t ) 1000 )

/* -------------------------------------------------------------------------- */
/* Scheduler                                                                  */
/* -------------------------------------------------------------------------- */

#define configUSE_PREEMPTION                     1
#define configUSE_TIME_SLICING                   1
#define configUSE_PORT_OPTIMISED_TASK_SELECTION  1
#define configUSE_TICKLESS_IDLE                  0
#define configMAX_PRIORITIES                     7
#define configMINIMAL_STACK_SIZE                 ( ( uint16_t ) 128 )
#define configMAX_TASK_NAME_LEN                  16
#define configTICK_TYPE_WIDTH_IN_BITS            TICK_TYPE_WIDTH_32_BITS
#define configIDLE_SHOULD_YIELD                  1
#define configENABLE_BACKWARD_COMPATIBILITY      1
#define configUSE_TASK_NOTIFICATIONS             1
#define configTASK_NOTIFICATION_ARRAY_ENTRIES    3
#define configQUEUE_REGISTRY_SIZE                8
#define configUSE_QUEUE_SETS                     0

/* -------------------------------------------------------------------------- */
/* Synchronization primitives                                                 */
/* -------------------------------------------------------------------------- */

#define configUSE_MUTEXES                        1
#define configUSE_RECURSIVE_MUTEXES              1
#define configUSE_COUNTING_SEMAPHORES            1
#define configUSE_NEWLIB_REENTRANT               0

/* -------------------------------------------------------------------------- */
/* Memory allocation                                                          */
/* -------------------------------------------------------------------------- */

#define configSUPPORT_STATIC_ALLOCATION          0
#define configSUPPORT_DYNAMIC_ALLOCATION         1
#define configTOTAL_HEAP_SIZE                    ( ( size_t ) ( 64 * 1024 ) )
#define configAPPLICATION_ALLOCATED_HEAP         0

/* -------------------------------------------------------------------------- */
/* Hooks                                                                      */
/* -------------------------------------------------------------------------- */

#define configUSE_IDLE_HOOK                      0
#define configUSE_TICK_HOOK                      0
#define configCHECK_FOR_STACK_OVERFLOW           2
#define configUSE_MALLOC_FAILED_HOOK             1
#define configUSE_DAEMON_TASK_STARTUP_HOOK       0

/* -------------------------------------------------------------------------- */
/* Runtime stats / trace                                                      */
/* -------------------------------------------------------------------------- */

#define configGENERATE_RUN_TIME_STATS            0
#define configUSE_TRACE_FACILITY                 1
#define configUSE_STATS_FORMATTING_FUNCTIONS     0

/* -------------------------------------------------------------------------- */
/* Software timers                                                            */
/* -------------------------------------------------------------------------- */

#define configUSE_TIMERS                         1
#define configTIMER_TASK_PRIORITY                ( configMAX_PRIORITIES - 1 )
#define configTIMER_QUEUE_LENGTH                 10
#define configTIMER_TASK_STACK_DEPTH             256

/* -------------------------------------------------------------------------- */
/* Optional API inclusions                                                    */
/* -------------------------------------------------------------------------- */

#define INCLUDE_vTaskPrioritySet                 1
#define INCLUDE_uxTaskPriorityGet                1
#define INCLUDE_vTaskDelete                      1
#define INCLUDE_vTaskCleanUpResources            0
#define INCLUDE_vTaskSuspend                     1
#define INCLUDE_vTaskDelayUntil                  1
#define INCLUDE_vTaskDelay                       1
#define INCLUDE_xTaskGetSchedulerState           1
#define INCLUDE_xTaskGetCurrentTaskHandle        1
#define INCLUDE_uxTaskGetStackHighWaterMark      1
#define INCLUDE_xTaskGetIdleTaskHandle           0
#define INCLUDE_eTaskGetState                    1
#define INCLUDE_xTimerPendFunctionCall           1
#define INCLUDE_xSemaphoreGetMutexHolder         1
#define INCLUDE_xQueueGetMutexHolder             1

/* -------------------------------------------------------------------------- */
/* Cortex-M / NVIC interrupt priorities                                       */
/* -------------------------------------------------------------------------- */

/* STM32H7 implements 4 priority bits, the lower 4 bits are read as zero. */
#define configPRIO_BITS                          4

/* Lowest possible interrupt priority (numerically largest). */
#define configLIBRARY_LOWEST_INTERRUPT_PRIORITY        15

/* Interrupts at or below this priority can use FreeRTOS API. Interrupts with
 * a numerically lower priority (i.e. higher logical priority) MUST NOT call
 * any FreeRTOS API. Keep this above NVIC priorities used by SysTick / TouchGFX
 * DMA / LTDC / DSI which we want to be FreeRTOS-aware. */
#define configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY   5

#define configKERNEL_INTERRUPT_PRIORITY \
    ( configLIBRARY_LOWEST_INTERRUPT_PRIORITY << ( 8 - configPRIO_BITS ) )

#define configMAX_SYSCALL_INTERRUPT_PRIORITY \
    ( configLIBRARY_MAX_SYSCALL_INTERRUPT_PRIORITY << ( 8 - configPRIO_BITS ) )

/* -------------------------------------------------------------------------- */
/* Interrupt handler names                                                    */
/* -------------------------------------------------------------------------- */

/* Direct routing: the FreeRTOS port's vPortSVCHandler / xPortPendSVHandler
 * ARE the exception handlers. They are __attribute__((naked)) and must be
 * entered by the hardware exception mechanism, NOT called via bl from a
 * trampoline (doing so corrupts EXC_RETURN / PSP and crashes the first
 * task). We therefore remap them to the Cortex-M vector-table names here.
 *
 * CubeMX still emits SVC_Handler / PendSV_Handler bodies in stm32h7xx_it.c
 * on every regen. To prevent a duplicate-symbol link failure, those bodies
 * are marked __attribute__((weak)) via a prior prototype placed inside the
 * USER CODE block of stm32h7xx_it.c, so the strong port.c definitions win. */
#define vPortSVCHandler         SVC_Handler
#define xPortPendSVHandler      PendSV_Handler

/* The SysTick_Handler is intentionally NOT remapped here: stm32h7xx_it.c
 * keeps its own SysTick_Handler that calls HAL_IncTick() and forwards to
 * xPortSysTickHandler() once the scheduler is running. */

/* -------------------------------------------------------------------------- */
/* Assert                                                                     */
/* -------------------------------------------------------------------------- */

#define configASSERT( x )                                              \
    do {                                                               \
        if( ( x ) == 0 ) {                                             \
            taskDISABLE_INTERRUPTS();                                  \
            for( ;; ) { __asm volatile( "bkpt #0" ); }                 \
        }                                                              \
    } while( 0 )

#endif /* FREERTOS_CONFIG_H */
